### ISSUE TITLE
Invalid SMILES string/processing Error

### ISSUE THREAD

**Issue by sculpturatus** [ccsb-scripps/bottchscore#3] opened 2021-05-13 19:44 UTC
Fantastic resource, thank you for the service.

Periodically I come across larger structures that cannot be processed. Mose recently Pibrentasvir:

Canonical SMILES:
CC(C(C(=O)N1CCCC1C2=NC3=C(N2)C=C(C(=C3)F)C4CCC(N4C5=CC(=C(C(=C5)F)N6CCC(CC6)C7=CC=C(C=C7)F)F)C8=CC9=C(C=C8F)N=C(N9)C1CCCN1C(=O)C(C(C)OC)NC(=O)OC)NC(=O)OC)OC

Isomeric SMILES:
C[C@H]([C@@H](C(=O)N1CCC[C@H]1C2=NC3=C(N2)C=C(C(=C3)F)[C@H]4CC[C@@H](N4C5=CC(=C(C(=C5)F)N6CCC(CC6)C7=CC=C(C=C7)F)F)C8=CC9=C(C=C8F)N=C(N9)[C@@H]1CCCN1C(=O)[C@H]([C@@H](C)OC)NC(=O)OC)NC(=O)OC)OC

They seem well-formed to me but I cannot get them to process.

**Comment by sforli** [comment] 2021-05-13 21:40
I'm glad you found it useful, thanks!

I have a hard time reproducing the problem. Did you try the offline code hosted here or the web service?
For the first structure I suspect it might run out of labels for alternative/equivalent atoms (>26 letters), which might be easy to fix.

For the second structure, I don't think it is a valid SMILES.

**Comment by sculpturatus** [comment] 2021-05-14 02:37
Dear Professor Forli,

Thank you for your response. I ran a large data set from the offline code,
and one of them seemed to have an unusually high complexity number (near
2100) so I wanted to check the value on the web tool and I only got an
error. The reason I feel that this value is unusually high is because of
high symmetry, despite being a large molecule, although perhaps it is just
very complex. When I put the two SMILES strings on GitHub it seems the
second one kept getting truncated - it should be as below. However, if
there is a 26 character limit then that explains the error.

Thanks kindly for your time,
Kevin A. Scott

C[C@H]([C@@H](C(=O)N1CCC[C@H]1C2=NC3=C(N2)C=C(C(=C3)F)[C@H]4CC[C@
@H](N4C5=CC(=C(C(=C5)F)N6CCC(CC6)C7=CC=C(C=C7)F)F)C8=CC9=C(C=C8F)N=C(N9)[C@
@H]1CCCN1C(=O)[C@H]([C@@H](C)OC)NC(=O)OC)NC(=O)OC)OC

**Comment by sforli** [comment] 2021-05-20 05:20
That seems to be a different problem altogether.
I'm running a few tests to figure out what's wrong, and why the server generates an error.
By the way, to do that, I had to change your lower-case hydrogens to upper-case, that does not seem to be standard nor supported by the OpenBabel library.

**Comment by sforli** [comment] 2021-05-21 03:56
Kevin,

I think I fixed the bug. As you correctly pointed out, this molecule has a high degree symmetry, higher than anything I've ever tested, so when generating the labels for symmetry-related atoms (e.g., C-1a, C-1b, etc...) it was running out of letters.
For the correct version of your SMILES:

`C[C@H]([C@@H](C(=O)N1CCC[C@H]1C2=NC3=C(N2)C=C(C(=C3)F)[C@H]4CC[C@@H(N4C5=CC(=C(C(=C5)F)N6CCC(CC6)C7=CC=C(C=C7)F)F)C8=CC9=C(C=C8F)N=C(N9[C@@H]1CCCN1C(=O)[C@H]([C@@H](C)OC)NC(=O)OC)NC(=O)OC)OC
`
I get a complexity of 697.03.
Take a look and let me know. If it works for you as well, I'll update the code here as well, and I'll close the issue.

**Closed as completed** 2022-01-10 18:33 UTC
