### ISSUE TITLE
Only get -h output

### ISSUE THREAD

**Issue by cmayerb1** [ccsb-scripps/bottchscore#4] opened 2022-01-07 17:15 UTC
When running bottchscore3.py as described in the ReadMe, the only time I get any output is when I use the -h flag (python bottchscore3.py -h).  When I try running the program using a single-molecule .smi file of adamantane (python bottchscore3.py -i adamantane.smi) the program seems to run but I get no output or error message.  I get the same result with any of the optional flags and by setting the debug flag in the code to True.

**Comment by sforli** [comment] 2022-01-10 18:12
I can't reproduce the bug without your input file.
Did you test the examples in the `examples` directory? 
Check that your SMILES file doesn't start with an invalid character or an empty line (which is invalid).

**Comment by cmayerb1** [comment] 2022-01-10 18:17
The input .smi file is attached.  I tested with the first example file in the “examples” directory, and with a .sdf version of the adamantane.smi file; the results were the same as before (no output message, error or otherwise, followed by the program’s exit).

**Comment by sforli** [comment] 2022-01-10 18:19
Can't see the attachment, if you replied to the email. You need to paste it into GitHub, I'm believe.

**Comment by cmayerb1** [comment] 2022-01-10 18:23
I see, sorry.  GitHub isn't allowing the .smi file type, so I've attached the same input file in a .txt format.  As mentioned, I get the same program output when using a file from the "examples" folder or when using a .sdf file instead of a .smi file.
[adamantane.txt](https://github.com/forlilab/bottchscore/files/7841075/adamantane.txt)

**Comment by sforli** [comment] 2022-01-10 18:30
It works for me:
```
$ python bottchscore3.py  -i adamantane.txt.smi                                                                                                                                               
16.17

$ python bottchscore3.py -v  -i adamantane.txt.smi                                                                                                                                                  
complexity [  1]:  1 * 1 * 1 log2( 4 * 2) = 3.0
complexity [  2]:  1 * 1 * 1 log2( 4 * 3) = 3.6
complexity [  3]:  1 * 1 * 1 log2( 4 * 2) = 3.0
complexity [  4]:  1 * 1 * 1 log2( 4 * 2) = 3.0
complexity [  5]:  1 * 1 * 1 log2( 4 * 3) = 3.6
complexity [  6]:  1 * 1 * 1 log2( 4 * 2) = 3.0
complexity [  7]:  1 * 1 * 1 log2( 4 * 3) = 3.6
complexity [  8]:  1 * 1 * 1 log2( 4 * 2) = 3.0
complexity [  9]:  1 * 1 * 1 log2( 4 * 3) = 3.6
complexity [ 10]:  1 * 1 * 1 log2( 4 * 2) = 3.0
         C-1    C-2     C-3     C-4     C-5     C-6     C-7     C-8     C-9     C-10
------------------------------------------------------------------------------------------
di       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     
ei       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     
si       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0     
Vi       4.0     4.0     4.0     4.0     4.0     4.0     4.0     4.0     4.0     4.0     
bi       2.0     3.0     2.0     2.0     3.0     2.0     3.0     2.0     3.0     2.0     
cmplx    3.00    3.58    3.00    3.00    3.58    3.00    3.58    3.00    3.58    3.00    
------------------------------------------------------------------------------------------
SMILES               : C1C2CC3CC(C2)CC1C3
Name                 : 
Intrinsic complexity : 16.17
Complexity/atom      : 1.62
==========================================================================================
```
I have no idea what the problem could be, but make sure you have the right Python modules and interpreter (>=3.x).
I'm going to close the issue, but if you find there's a bug you can re-open it.

**Closed as completed by sforli** 2022-01-10 18:30 UTC

**Comment by cmayerb1** [comment] 2022-01-10 19:00
I think the issue is partly due to the operating system, since the errors I originally described were in the Windows command line.  Switching to the Linux environment with OpenBabel (Ubuntu 20.04.2, Python 3.8, Openbabel 3.0.0), I now get an error message saying that "OpenBabel >v.3 is required".  While I'm glad I'm getting some kind of output, it doesn't make sense since I have OpenBabel 3.0.0 installed in my Linux environment.

**Comment by sforli** [comment] 2022-01-10 19:06
It sounds like an issue with your environment.
Try this:
```python -c "from openbabel import openbabel as ob"```
If you get an error, it means that either your interpreter is not the right one, or you have problems with your PATH variable.
Try `python3`, or `which python` and see if it's running the one you were expecting.

In the meantime, I'll keep the issue close since it's not related to the code itself.
You can try also writing to the [AutoDock mailing list](https://autodocksuite.scripps.edu/support/), there have been a few discussions about the Bottcher score there.

**Comment by cmayerb1** [comment] 2022-01-10 20:50
I followed the instructions from OpenBabel for Python bindings in Linux.  Running your test line gives the following error:
`python3 -c "from openbabel import openbabel as ob"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'openbabel' from 'openbabel' (unknown location)`
Changing the first line to `python3 -c "import openbabel as ob` gave me no error.
I'm still getting the error about the OpenBabel version though.

**Comment by sforli** [comment] 2022-01-10 21:48
I think you have a few conflicting issues here, including multiple Python interpreters, and module installations.

The easiest way to fix this could be start from a clean slab. 
Try installing [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html), then install the latest [OpenBabel](https://anaconda.org/conda-forge/openbabel).
Hope this helps.

**Comment by cmayerb1** [comment] 2022-01-12 19:29
Tested the code in a conda environment using Spyder; I kept the BottchScore class unchanged but changed the input to only evaluate adamantane.  The class works as described, but I can't run the modified script outside of that conda environment.  It seems like it's an issue with the OpenBabel Python bindings, which have been an ongoing problem in Windows environments from what I can find.
